language: bash

env:
  - aws_cli_version
  - aws_acc_num=674726326575
  - aws_region=eu-west-1
  - image_version=v4

before_install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${aws_cli_version}.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - export PATH=$PATH:$HOME/.local/bin
  - aws --version

jobs:
  include:
    - stage: build docker image
      if: NOT branch = master
      script:
        - aws s3 ls

# TODO