language: bash

env:
  - aws_acc_num=674726326575
  - aws_region=eu-west-1
  - image_version=v4

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin

jobs:
  include:
    - stage: build docker image
      if: branch = master
      script:
      - aws s3 ls
      # - aws ecr get-login-password --region ${aws_region} | docker login --username AWS --password-stdin ${aws_acc_num}.dkr.ecr.eu-west-1.amazonaws.com
      # - docker build -t mern-stack:{image_version}
      # check to see if image exists yet
      # - docker tag mern-stack:{image_version} {aws_acc_num}.dkr.ecr.{aws_region}.amazonaws.com/mern-stack:{image_version}
      # - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
    

