language: bash

env:
  - aws_cli_version
  - aws_acc_num=674726326575
  - aws_region=eu-west-1
  - image_version=v4

before_install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${aws_cli_version}.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - export PATH=$PATH:$HOME/.local/bin
  - aws --version

jobs:
  include:
    - stage: build docker image
      if: NOT branch = master
      script:
        - aws s3 ls
      # - aws ecr get-login-password --region ${aws_region} | docker login --username AWS --password-stdin ${aws_acc_num}.dkr.ecr.eu-west-1.amazonaws.com
      # - docker build -t mern-stack:{image_version}
      # check to see if image exists yet
      # - docker tag mern-stack:{image_version} {aws_acc_num}.dkr.ecr.{aws_region}.amazonaws.com/mern-stack:{image_version}
      # - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
